import '../app/globals.css';
import React from 'react';
import Link from 'next/link';
import Head from 'next/head';
// /src/pages/index.tsx
import { auth } from '../firebaseConfig';

// 登入函數
const login = async (email: string, password: string) => {
  try {
    await auth.signInWithEmailAndPassword(email, password);
    // 登入成功後的處理...
  } catch (error) {
    console.error(error);
    // 處理錯誤...
  }
};

export default function Home() {
    return (
      
      <div className="flex flex-col h-screen justify-center items-center bg-white">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        {/* 主容器 */}
        <div className="bg-pink-100 p-6 rounded-lg shadow-md">
          {/* 主標題部分 */}
          <div className="bg-pink-600 text-white p-8 text-center">React 練習專案</div>
          
          {/* 歡迎訊息部分 */}
          <div className="bg-pink-500 text-white p-8 text-center ">歡迎光臨我的專頁</div>
          
          {/* 按鈕部分 */}
          <div className=" flex justify-center p-8 bg-white">
            <Link href="/accounting">
              <button className="text-pink-400 p-1 border border-pink-400 rounded hover:bg-pink-100">點此開始</button>
            </Link>
          </div>
        </div>
      </div>
    );
}
